spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.99.100:3401/records
    username: root
    password: dev
    driver-class-name: com.mysql.jdbc.Driver
  logging:
    level:
      root: WARN
      org.springframework.web: INFO
      org.springframework.security: INFO
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false